DROP DATABASE IF EXISTS MWP
GO
CREATE DATABASE MWP
GO
USE MWP
GO

CREATE TABLE IF NOT EXISTS clients (
    `idClient` INT PRIMARY KEY AUTO_INCREMENT,
    `nom` VARCHAR(255) NOT NULL UNIQUE,
    `telèfon` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS vehicles (
    `idVehicle` INT PRIMARY KEY AUTO_INCREMENT,
    `matrícula` VARCHAR(255) NOT NULL UNIQUE,
    `model` VARCHAR(255) NOT NULL,
    `any` INT NOT NULL,
    `idClient` INT NOT NULL,
    FOREIGN KEY (`idClient`) REFERENCES clients(`idClient`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Cites (
    `idCita` INT PRIMARY KEY AUTO_INCREMENT,
    `data` DATE NOT NULL,
    `servei sol·licitat` TIME NOT NULL,
    `idClient` INT NOT NULL,
    `idVehicle` INT NOT NULL,
    FOREIGN KEY (`idClient`) REFERENCES clients(`idClient`) ON DELETE CASCADE,
    FOREIGN KEY (`idVehicle`) REFERENCES vehicles(`idVehicle`) ON DELETE CASCADE
);